spring:
  datasource:
    url: jdbc:mysql://localhost:3306/family_story  # ?? ?????? ???? ??
    username: gangnam  # ??? ??
    password: gangnam  # ????
  jpa:
    hibernate:
      ddl-auto: update  # ??? ?? ????
      show-sql: true  # SQL ?? ?? ??
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # Hibernate ?? ??

server:
  port: 8080  # ?? ?? ??
